<!doctype html>

<html>

<head>
  <meta charset="utf-8">
  <title>Yatra â€“ Showcase</title>

  <style>
    HTML,
    BODY
    {
      background: #F0F0F0;
      padding: 0;
      margin: 0;
      height: 100%;
    }
    BODY
    {
      overflow-y: scroll;
    }
  </style>

  <script src="../node_modules/basisjs/src/basis.js" data-basis-config="
    noConflict: true,
    exports: true,
    modules: {
      esprima: '../node_modules/esprima/',
      diff: '../node_modules/diff/dist/diff.js',
      runner: {
        path: '../src/runner',
        filename: './index.js'
      },
      app: {
        autoload: true,
        path: '../src/app',
        filename: './index.js'
      }
    }
  "></script>
</head>

<body>
  <div id="test-runner"></div>
  <script>
    yatra.setup({
      element: document.getElementById('test-runner')
    });
    yatra.loadTests({
      name: 'Showcase',
      test: [
        {
          name: 'Test done',
          test: function(){
            assert(true, true);
          }
        },
        {
          name: 'Comparison',
          test: [
            {
              name: 'Non-strict comparation',
              test: function(){
                assert(12.34, 12.34);
                assert({ a: 1, b: 2 }, { b: 2, a: 1 });
                assert([1, 2, 3], [1, 2, 3]);
                assert(/foo/, /foo/);
                assert(new Date, new Date);
                assert(new String, new String);
                assert(new Number, new Number);
                assert(new Boolean, new Boolean);
                assert(NaN, NaN);
                assert(
                  function(){ return 123; },
                  function(){ return 123; }
                );
                assert(
                  function(){
                    function foo(){
                      return location;
                    };
                    assert(1, 1);
                    return foo();
                  },
                  function(){
                    function foo(){
                      return location;
                    };
                    assert(1, 1);
                    return foo();
                  }
                );

                var foo = function(){ return assert(1, 1); };
                assert(function(){ return assert(1, 1); }, foo);

                // function bar(){ return assert(1, 1); };
                // assert(function bar(){ return assert(1, 1); }, bar);
              }
            },
            {
              name: 'Failures',
              test: function(){
                assert(true, false);
                assert({ a: 1, b: 2 }, { a: 1, c: 2 });
                assert([{ a: 1 }], [{ a: 1 }]);
                assert([1, 2], [2, 3]);
                assert(/foo/, /bar/);
                assert(/foo/g, /foo/);
                assert('This is expected string', 'This is actual string');
                assert(new Date(0), new Date(2000));
                assert(new String('foo'), new String('bar'));
                assert(new Number(1), new Number(2));
                assert(new Boolean(true), new Boolean(false));
                assert(
                  function(){ return 123; },
                  function(){ return 456; }
                );
              }
            }
          ]
        },
        {
          name: 'Exception in TOC',
          test: function(){
            asd();
          }
        },
        {
          name: 'Exceptions',
          test: [
            {
              name: 'Regular exception',
              test: function(){
                var foo = 123;

                // exception on that line
                foo.exception();

                assert(123, foo);
              }
            },
            {
              name: 'Exception inside function expression',
              test: function(){
                [1, 2, 3].forEach(function(){
                  // exception on that line
                  assert(0, ++test);
                });

                assert(true, true);
              }
            },
            {
              name: 'Exception inside function declaration',
              test: function(){
                function decl(){
                  // exception on that line
                  assert(0, ++test);
                }

                decl();

                assert(true, true);
              }
            },
            {
              name: 'Exception in setTimeout',
              test: function(done){
                setTimeout(function(){
                  // exception on that line
                  assert(0, ++test);
                }, 10);
              }
            },
            {
              name: 'Exception inside function declaration invoked by setTimeout',
              test: function(done){
                function decl(){
                  // exception on that line
                  assert(0, ++test);
                }

                setTimeout(decl, 10);
              }
            },
            {
              name: 'Assert exception',
              test: function(){
                var foo = 123;

                assert.exception(function(){
                  // exception on that line
                  foo.exception();
                });

                assert(foo === 123);
              }
            },
            {
              name: 'Assert exception',
              test: function(){
                var foo = 123;

                assert.exception(function(){
                  // nothing to do, assert failed
                });

                assert(foo === 123);
              }
            }
          ]
        },
        {
          name: 'Pending',
          test: [
            {
              name: 'Empty tests are pending',
              test: function(){}
            },
            {
              name: 'Tests with no `test` property are pending'
            },
            {
              name: 'Tests with no assertions are pending',
              test: function(){
                var nothing;
              }
            },
            {
              name: 'Tests marked as pending are pending and doesn\'t execute',
              pending: true,
              test: function(){
                assert(true, true);
              }
            },
            {
              name: 'Empty test suites are pending',
              test: []
            },
            {
              name: 'Empty test suites with only pending tests are OK',
              test: [
                {
                  name: 'Test with empty test function',
                  test: function(){}
                },
                {
                  name: 'Test with no test'
                }
              ]
            }
          ]
        },
        {
          name: 'Async (tests may nest)',
          test: [
            {
              name: 'Test with done callback',
              test: function(done){
                assert(true, true);
                done();
              }
            },
            {
              name: 'Test with done callback that never called fails by timeout',
              test: function(done){
                assert(true, true);
              }
            },
            {
              name: 'this.async()',
              test: function(){
                var num = 0;

                this.async(function(){
                  assert(2, ++num);
                });

                this.async(function(){
                  assert(3, ++num);
                });

                assert(1, ++num);
              }
            },
            {
              name: 'nested this.async()',
              test: function(){
                var num = 0;

                this.async(function(){
                  assert(2, ++num);
                  this.async(function(){
                    assert(4, ++num);
                    this.async(function(){
                      assert(5, ++num);
                    });
                  });
                });

                this.async(function(){
                  assert(3, ++num);
                });

                assert(1, ++num);
              }
            },
            {
              name: 'this.async() should not cause on exception',
              test: function(){
                var num = 0;

                this.async(function(){
                  assert(1, ++num);
                });

                assert(true, ++exception);
              }
            },
            {
              name: 'first exception in this.async() should stops others',
              test: function(){
                this.async(function(){
                  assert(1, ++num);
                });

                this.async(function(){
                  assert(2, ++num);
                });
              }
            },
            {
              name: 'this.async() that infinitely call async fails by timeout',
              test: function(){
                this.async(function infinite(){
                  this.async(infinite);
                });
              }
            }
          ]
        },
        {
          name: 'nested test',
          test: [
            {
              name: 'level 2',
              test: [
                {
                  name: 'level 3',
                  test: [
                    {
                      name: 'level 4',
                      test: function(){
                        assert(true === true);
                        assert(true === false);
                      }
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          name: 'Promise',
          test: [
            {
              name: 'should end test on promise resolve successful',
              test: function(){
                return new Promise(function(resolve, reject){
                  resolve('ok');
                });
              }
            },
            {
              name: 'should end test for resolved promise',
              test: function(){
                return Promise.resolve('ok');
              }
            },
            {
              name: 'test promise',
              test: function(){
                return new Promise(function(resolve, reject){
                  resolve('ok');
                }).then(function(data){
                  assert(data === 'ok');
                  assert(data === 'wrong');
                });
              }
            },
            {
              name: 'should end test on promise reject',
              test: function(){
                return new Promise(function(resolve, reject){
                  reject(new Error('ok'));
                });
              }
            },
            {
              name: 'should end test for rejected promise',
              test: function(){
                return Promise.reject(new Error('ok'));
              }
            },
            {
              name: 'test rejected promise',
              test: function(){
                return Promise.reject(new Error('ok')).then(function(){
                  throw new Error('shouldn\'t to be resolved');
                }, function(){
                  return 'ok';
                }).then(function(data){
                  assert(data === 'ok');
                }, function(){
                  assert(false);
                });
              }
            },
            {
              name: 'test rejected promise (should fail)',
              test: function(){
                return Promise.resolve('wrong').then(function(){
                  throw new Error('shouldn\'t to be resolved');
                }, function(){
                  return 'ok';
                }).then(function(data){
                  assert(data === 'ok');
                }, function(){
                  assert(false);
                });
              }
            },
            {
              name: 'should timeout when promise doesn\'t resolve',
              test: function(){
                return new Promise(function(){});
              }
            }
          ]
        }
      ]
    });
    yatra.run();
  </script>
</body>
</html>
